name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Clean Install Dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules
        npm install
      
    - name: Build
      run: |
        npm run build
        ls -la dist/ # Verify build output
    
    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/home/snoxpro-gallery/htdocs/gallery.snoxpro.com"
        strip_components: 1
    
    - name: Restart PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/snoxpro-gallery/htdocs/gallery.snoxpro.com
          pm2 restart snox_photoselection
